### PR TITLE
Update attributeChangedCallback() to be more concrete.

### PR DESCRIPTION
**Pull request by depeele**
When the target property is defined as 'Boolean':
- if the value indicates the absence of the attribute ( 'false', 'null', false, null ) ensure the attribute is actually absent/removed;

When the target property is defined as 'String':
- if the value represents an empty string ( '', 'null', false, null, undefined ) ensure the attribute is absent/removed;

Pass the more concrete property value to `_propertiesChanged()` instead of the "fuzzy" attribute value.

### CODE REVIEW

**Comment by DerDrodt** [comment]
Wow! Your changes are really great. I just changed the project to Typescript to make it easier for developers to work with. I will just move these changes into the ts files, if that's fine with you.

Thank you so much for working on this project!

**Comment by DerDrodt** [comment]
If you are happy with my implementation of your changes and I haven't forgotten anything, I will close your PR.

Just let me know.

**Comment by depeele** [comment]
Wow! That was quick!

The changes look good to me. There is one additional change that I pushed after your updates.

I forgot to handle the `observedAttributes` so I pulled the conversion into a local function and used it for both the `observedAttributes` getter as well as the `constructor`

**Comment by DerDrodt** [comment]
That's really good. Just added it as well.

Another change I made is that I removed the shorthand version of property declaration. so something like
`myProperty: String`
now has to be:
`myProperty: { type: String }`

I did that, because I rarely use the short version and it made the code a bit more tedious. 

What do you think? Should I bring it back?

**Comment by depeele** [comment]
Depends on how Polymer-like you want to be...

It is a nice short-hand, and if the additional code isn't too much, you may want to leave it as an option...

But, it's your call.

**Comment by DerDrodt** [comment]
Added the short version back and I am now closing this PR.

I would be very thankful, if you had any other ideas or improvements.

**Pull request closed without merging**
